<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>TwitchAnnouncer</PackageId>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/HollieShadbolt/TwitchAnnouncer</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Twitch" Version="0.0.1" />
    </ItemGroup>
</Project>
